# Generated by Django 4.2.4 on 2024-11-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_nummber',
            new_name='phone_number',
        ),
    ]
