# Generated by Django 4.2.4 on 2024-11-03 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_phone_nummber_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
