# Generated by Django 4.2.4 on 2024-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(choices=[('avatars/avatar1.png', 'Avatar 1'), ('avatars/avatar2.png', 'Avatar 2'), ('avatars/avatar3.png', 'Avatar 3'), ('avatars/avatar4.png', 'Avatar 4')], default='avatars/avatar1.png', upload_to='avatars/'),
        ),
    ]
