# Generated by Django 4.2.4 on 2024-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=6)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(default=1234, max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatars/avatar1.jpg', 'Avatar 1'), ('avatars/avatar2.jpg', 'Avatar 2'), ('avatars/avatar3.jpg', 'Avatar 3'), ('avatars/avatar4.jpg', 'Avatar 4')], default='avatars/avatar1.jpg', max_length=100),
        ),
    ]
