# Generated by Django 4.2.4 on 2024-11-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_deposit_customuser_pin_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(default=1234),
        ),
    ]
