# Generated by Django 4.2.4 on 2024-11-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_customuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
